name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          echo "ANYKERNEL_SOURCE=$(cat config.env | grep -w "ANYKERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "ANYKERNEL_SOURCE_BRANCH=$(cat config.env | grep -w "ANYKERNEL_SOURCE_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "KERNEL_SOURCE=$(cat config.env | grep -w "KERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "KERNEL_SOURCE_BRANCH=$(cat config.env | grep -w "KERNEL_SOURCE_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "KERNEL_CONFIG=$(cat config.env | grep -w "KERNEL_CONFIG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "BUILD_ARGS=$(cat config.env | grep -w "BUILD_ARGS" | head -n 1 | cut -d ":" -f 2)" >> $GITHUB_ENV
          sudo apt-get update
          sudo apt-get install -y bc ccache flex bison libssl-dev \
          make clang lld libelf-dev git unzip curl zip libncurses-dev
          sudo ln -s /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5 || true

      - name: Setup Neutron Clang Toolchain Path
        run: |
          echo "Adding Neutron Clang to PATH"
          echo "PATH=/home/runner/toolchains/neutron-clang/bin:$PATH" >> $GITHUB_ENV
          echo "Path added successfully"

      - name: Pull toolchain (Neutron Clang)
        run: |
          git clone --depth=1 https://github.com/Neutron-Toolchains/antman.git
          cd antman
          bash antman -S
          cd ..

      - name: Pull kernel source
        run: |
          git clone --depth=1 ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} kernel-source

      - name: Build kernel
        run: |
          export KBUILD_BUILD_USER="Fraschze97"
          export PATH=$GITHUB_WORKSPACE/toolchains/neutron-clang/bin:${PATH}  # Ensure Neutron Clang is in PATH
          args="ARCH=arm64 \
                O=../out \
                ${{ env.BUILD_ARGS }} \
                CLANG_TRIPLE=aarch64-linux-gnu- \
                CROSS_COMPILE=$GITHUB_WORKSPACE/toolchains/neutron-clang/bin/aarch64-linux-gnu- \
                CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/toolchains/neutron-clang/bin/arm-linux-gnueabi-"
          cd kernel-source
          ./scripts/clean.sh  # Clean up the kernel source tree
          make ${args} ${{ env.KERNEL_CONFIG }}
          make -j$(nproc --all) ${args}

      - name: Upload Log to Telegram (if failed)
        if: failure()
        env:
          BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -F document=@"build.log" \
            "https://api.telegram.org/bot$BOT_TOKEN/sendDocument?chat_id=$CHAT_ID&caption=Log%20Error%20Build%20Kernel"

      - name: Clone AnyKernel3 & Copy Files
        run: |
          git clone --depth=1 "$ANYKERNEL_SOURCE" -b "$ANYKERNEL_SOURCE_BRANCH" AnyKernel3
          rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md
          if [[ -f out/arch/arm64/boot/Image.gz-dtb ]]; then
            cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
          elif [[ -f out/arch/arm64/boot/Image-dtb ]]; then
            cp out/arch/arm64/boot/Image-dtb AnyKernel3/Image-dtb
          elif [[ -f out/arch/arm64/boot/Image.gz ]]; then
            cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
          elif [[ -f out/arch/arm64/boot/Image ]]; then
            cp out/arch/arm64/boot/Image AnyKernel3/Image
          fi
          if [[ -f out/arch/arm64/boot/dtbo.img ]]; then
            cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
          fi

      - name: Set build date
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Make flashable zip
        run: |
          cd AnyKernel3
          zip -r "../DreamsKernel-${BUILD_DATE}.zip" * .[^.]* -x "*.git*" -x "README.md"

      - name: Upload to GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DreamsKernel-${{ env.BUILD_DATE }}
          path: DreamsKernel-${{ env.BUILD_DATE }}.zip

      - name: Upload to Telegram
        env:
          BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -F document=@"DreamsKernel-${BUILD_DATE}.zip" \
            -F chat_id=$CHAT_ID \
            -F caption="DreamsKernel build $BUILD_DATE" \
            https://api.telegram.org/bot$BOT_TOKEN/sendDocument
