name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Load config.env to environment
        run: |
          set -a
          source config.env
          set +a

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc ccache flex bison libssl-dev \
              make clang lld libelf-dev git unzip curl zip libncurses-dev
          sudo ln -s /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5 || true

      - name: Pull toolchain
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 aarch64-linux-android-4.9
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 arm-linux-androideabi-4.9
          git clone https://github.com/xiangfeidexiaohuo/Snapdragon-LLVM.git clang

      - name: Pull kernel source
        run: |
          git clone --depth=1 "$KERNEL_SOURCE" -b "$KERNEL_SOURCE_BRANCH" kernel-source

      - name: Integrate KernelSU
        run: |
          cd kernel-source
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5

      - name: Build kernel
        run: |
          export KBUILD_BUILD_USER="Fraschze97"
          export PATH=$GITHUB_WORKSPACE/clang/bin:${PATH}
          args="ARCH=arm64 \
                O=../out \
                $BUILD_ARGS \
                CLANG_TRIPLE=aarch64-linux-gnu- \
                CROSS_COMPILE=$GITHUB_WORKSPACE/aarch64-linux-android-4.9/bin/aarch64-linux-android- \
                CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-"
          cd kernel-source
          clang -v &> ../build.log
          make $args "$KERNEL_CONFIG" &>> ../build.log
          make -j$(nproc --all) $args &>> ../build.log

      - name: Upload Log to Telegram (if failed)
        if: failure()
        env:
          BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -F document=@"build.log" \
            "https://api.telegram.org/bot$BOT_TOKEN/sendDocument?chat_id=$CHAT_ID&caption=Log%20Error%20Build%20Kernel"

      - name: Clone AnyKernel3 & Copy Files
        run: |
          git clone --depth=1 "$ANYKERNEL_SOURCE" -b "$ANYKERNEL_SOURCE_BRANCH" AnyKernel3
          rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md
          if [[ -f out/arch/arm64/boot/Image.gz-dtb ]]; then
            cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
          elif [[ -f out/arch/arm64/boot/Image-dtb ]]; then
            cp out/arch/arm64/boot/Image-dtb AnyKernel3/Image-dtb
          elif [[ -f out/arch/arm64/boot/Image.gz ]]; then
            cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
          elif [[ -f out/arch/arm64/boot/Image ]]; then
            cp out/arch/arm64/boot/Image AnyKernel3/Image
          fi
          if [[ -f out/arch/arm64/boot/dtbo.img ]]; then
            cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
          fi

      - name: Set build date
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Make flashable zip
        run: |
          cd AnyKernel3
          zip -r "../DreamsKernel-${BUILD_DATE}.zip" * .[^.]* -x "*.git*" -x "README.md"

      - name: Upload to GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DreamsKernel-${{ env.BUILD_DATE }}
          path: DreamsKernel-${{ env.BUILD_DATE }}.zip

      - name: Upload to Telegram
        env:
          BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -F document=@"DreamsKernel-${BUILD_DATE}.zip" \
            -F chat_id=$CHAT_ID \
            -F caption="DreamsKernel build $BUILD_DATE" \
            https://api.telegram.org/bot$BOT_TOKEN/sendDocument
